[project]
name = "ngiab-cal"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "colorama>=0.4.6",
    "hydrotools-nwis-client>=4.1.0",
    "pandas>=2.2.3",
]

[project.scripts]
ngiab-cal = "ngiab_cal.__main__:main"

[dependency-groups]
dev = ["ruff>=0.11.6"]

[tool.ruff]
line-length = 100

[build-system]
requires = ["setuptools", "setuptools-scm"]
