[project]
name = "cfundata2"
version = "0.2.2"
description = "my data"
readme = "README.md"
authors = [
    { name = "zoushucai", email = "zoushucai@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
cfundata2 = "cfundata2:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-autorefs>=1.4.1",
    "mkdocs-material>=9.6.12",
    "mkdocstrings[python]>=0.29.1",
    "pytest>=8.3.5",
    "pandas>=1.5.0",
    "pyarrow>=17.0.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]          #将测试发现路径设置为tests目录。
python_files = "test_*.py"    #指定测试文件应以test_开头。
python_functions = "test_*"   #指定测试函数应以test_开头。
