[tool.poetry]
name = "aevoo-pycontrol"
version = "0.1.1"
description = ""
authors = ["David Casier <david.casier@aevoo.fr>"]
# readme = "README.md"
packages = [{ include = "aevoo_pycontrol", format = "wheel" }]
include = [
    "aevoo_pycontrol/**/*.py",
]

[tool.poetry.dependencies]
httpx = "^0.27.2"               # BSD-3
pydantic = "^2.11"              # MIT
PyYAML = "^6.0"                 # MIT
python = "^3.12"                # PSF-2

[tool.poetry.group.dev.dependencies]
ariadne-codegen = "^0.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ariadne-codegen]
schema_path = "../../../gql/control/generated/schema.graphql"
queries_path = "./_concatened.gql"
# target_package_name = "aevoo_pycontrol"
target_package_path = "aevoo_pycontrol"
