[project]
name = "platformeb"
version = "0.1.1"
description = ""
authors = [
    {name = "Yan",email = "119687802+sndmndss@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "selenium (>=4.31.0,<5.0.0)",
    "appium-python-client (>=5.0.0,<6.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "webdriver-manager (>=4.0.2,<5.0.0)"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
include = [
    "platformeb"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
