[build-system]
requires = ["setuptools>=61.0.0", "wheel", "cython", "cibuildwheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dart-bridge"
version = "0.4.1"
description = "A Python C extension for interacting with the Dart SDK from Python"
readme = "README.md"
authors = [
    { name = "Flet Team", email = "hello@flet.dev" },
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C",
    "Programming Language :: Cython",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["dart", "ffi", "bridge", "cython"]

[project.urls]
Homepage = "https://github.com/flet-dev/dart-bridge"
Issues = "https://github.com/flet-dev/dart-bridge/issues"