[tool.poetry]
name = "pywattbox"
version = "0.8.0"
description = "A python wrapper for WattBox APIs."
license = "MIT"
readme = "README.md"
authors = ["Erik Seglem <erik.seglem@gmail.com>"]
repository = "https://github.com/eseglem/pywattbox"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Home Automation",
]

[tool.poetry.dependencies]
python = "^3.10"
asyncssh = { version = ">=2.2.1,<3.0.0", optional = true }
beautifulsoup4 = { version = ">=4.11.0", optional = true }
h11 = { version = ">=0.14.0", optional = true }
httpx = { version = ">=0.23.0", optional = true }
lxml = { version = ">=4.9.0", optional = true }
scrapli = { version = ">=2023.7.30", optional = true }
ssh2-python = { version = ">=0.23.0,<2.0.0", optional = true }

[tool.poetry.extras]
ip = ["scrapli", "asyncssh"]
http = ["httpx", "beautifulsoup4", "lxml", "h11"]
ssh2 = ["scrapli", "ssh2-python"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = { version = "^1.9" }
pre-commit = { version = "*" }
ruff = { version = "*" }
types-beautifulsoup4 = { version = "*" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
fix = true

[tool.ruff.lint]
select = [
    "F",   # pyflakes
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "I",   # isort
    "YTT", # flake8-2020
    "C4",  # flake8-comprehensions
    "B",   # flake8-bugbear
]
ignore = [
    "E501", # Line too long. Handled by black.

]

[tool.ruff.isort]
combine-as-imports = true

[tool.mypy]
python_version = "3.10"
show_error_codes = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
