[project]
name = "viby"
version = "0.0.24"
description = "Viby vibes everything"
authors = [
    { name = "JohanLi233", email = "li_zhonghan@qq.com" }
]
readme = "README.md"
license = { text = "GPL-3.0" }  # 添加license声明
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.2.7",
    "openai>=1.76.2",
    "pocketflow>=0.0.2",
    "prompt-toolkit>=3.0.51",
    "pyperclip>=1.9.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "rich>=14.0.0",
    "ruff>=0.11.7",
]

[tool.setuptools.packages.find]
include = ["viby*"]
exclude = ["assets*"]

[project.scripts]
yb = "viby.cli.main:main"
