












[project]
name = "i_principal_central"
version = "0.6.13"
description = "i simple Python library"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
  { name="i_principal_central", email="deboubil24@gmail.com" }
]
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"










