[project]
name = "geoaiagent"
version = "0.1.15"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mcp"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
geoaiagent = "geoaiagent.__main__:thisismain"

