[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "an_symlinksutility"
version = "0.1.1"
description = "A package for an_symlinksutility."
authors = [
    { name = "Atsushi888", email = "vtgrotxu@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6"
dependencies = ['an_EnvManager']

[project.urls]
Homepage = "https://github.com/Atsushi888/an_symlinksutility"
Repository = "https://github.com/Atsushi888/an_symlinksutility"
