[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fixthis"
version = "0.1.6"
description = "A small Python library that provides some 'QOL' features"
authors = [
  { name = "Konstantin", email = "assembly@codemania.net" }
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
license = { file = "LICENSE" }
dependencies = []

# setuptools configuration for src layout
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]
