[tool.poetry]
name = "jerkup"
version = "2.1.0"
description = "Hamster Uploader"
license = "MIT"
authors = ["deadmaster <deadmaster@noreply.codeberg.org>"]
readme = "README.md"
repository = "https://codeberg.org/deadmaster/jerkup"
classifiers = ["Topic :: Internet :: WWW/HTTP"]

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.3"
requests-toolbelt = "^1.0.0"
msgspec = "^0.19.0"
platformdirs = "^4.3.8"

[tool.poetry.group.dev.dependencies]
mypy = "^1.15.0"
ruff = "^0.11.9"
types-requests = "^2.32.0"

[tool.poetry.scripts]
jerkup = "jerkup.__main__:main"

[tool.ruff]
include = ["jerkup/**/*.py"]
target-version = "py313"
line-length = 100
indent-width = 4

[tool.ruff.lint]
select = ["F", "I", "UP", "G"]
ignore = ["UP007", "UP015", "UP032", "UP038"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
skip-magic-trailing-comma = true

[tool.mypy]
python_version = "3.13"
show_error_codes = true
show_absolute_path = true
files = ["jerkup"]
strict = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
