[project]
name = "mistune-slack"
version = "0.1.3"
description = "Convert Markdown to Slack blocks - useful for chatbots"
readme = "README.md"
authors = [
    { name = "Ryan Munro", email = "500774+munro@users.noreply.github.com" },
]
requires-python = ">=3.11,<4"
dependencies = ["mistune>=3,<4", "typing-extensions>=4.13.2"]
license = { text = "MIT" }
keywords = ["slack", "markdown", "mistune", "block-kit", "renderer"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries",
    "Topic :: Text Processing :: Markup",
]

[project.urls]
Homepage = "https://github.com/Submersible/python-mistune-slack"
Repository = "https://github.com/Submersible/python-mistune-slack"
Documentation = "https://github.com/Submersible/python-mistune-slack#readme"
"Bug Tracker" = "https://github.com/Submersible/python-mistune-slack/issues"

[project.scripts]
test = "pytest:main"

[dependency-groups]
dev = [
    "ipython>=9.2.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.4.2",
    "loguru>=0.7.3",
    "pytest>=8.3.5",
    "rich[jupyter]>=14.0.0",
    "ruff>=0.11.8",
    "tqdm>=4.67.1",
    "wat-inspector>=0.4.3",
]

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 120
respect-gitignore = false
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"]
per-file-ignores = { "*.ipynb" = ["F811", "E402", "F841", "F401"] }

[tool.pytest.ini_options]
addopts = "--doctest-modules"
python_files = "*.py"

[tool.pyright]
reportMissingModuleSource = false
reportPrivateImportUsage = false
typeCheckingMode = "standard"
include = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
