[project]
name = "ceeteem"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "coparaoji", email = "coparaoji@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
