[project]
name = "harrix-pylib"
version = "0.116"
description = "Common functions for working in Python"
readme = "README.md"
license = { file = "LICENSE.md" }
authors = [{ name = "Anton Sergienko", email = "anton.b.sergienko@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
    "libcst>=1.6.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "ruff>=0.9.2",
]

[project.scripts]
harrix-pylib = "harrix_pylib:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "isort>=5.13.2",
    "pytest>=8.3.4",
    "vermin>=1.6.0",
]

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
addopts = "-m 'not slow'"

markers = ["slow: mark a test as slow."]
