[project]
name = "test-mcp-server"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.7.1",
]


[project.scripts]
test-mcp-server = "mcp_server.server:main"
