[project]
name = "manim_ai"
version = "0.4.3"
description = "Merging Manim & AI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
    "latex>=0.7.0",
    "libcst>=1.7.0",
    "ipython>=8.31.0",
    "httpx>=0.28.1",
    "lmstudio>=1.3.0",
]

[build-system]
requires = ["setuptools>=80.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["mainim"]

