[tool.poetry]
name = "anyvec"
version = "0.1.8"
description = "A Python package for seamless vectorization for any content type"
authors = ["Mark Shteyn <markshteyn1@gmail.com>"]
readme = "README.md"
packages = [{ include = "anyvec" }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pillow = "10.4.0"
ruff = "0.11.8"
requests = "2.32.3"
numpy = "2.2.5"
pymupdf = "1.25.5"
pdfplumber = "0.11.6"
python-docx = "1.1.0"
mammoth = "1.9.0"
openpyxl = "3.1.5"
xlrd = "2.0.1"
odfpy = "1.4.1"
python-pptx = "1.0.2"
ebooklib = "0.19"
beautifulsoup4 = "4.13.4"
opencv-python = "4.11.0.86"
moviepy = "2.1.2"
markdown = "3.8"
pdfkit = "1.0.0"
weasyprint = "65.1"
pillow-heif = "0.22.0"
pillow-avif-plugin = "1.5.2"
wand = "0.6.13"
av = "14.3.0"
striprtf = "^0.0.29"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
python-dotenv = "^1.1.0"


[tool.poetry.extras]
audio = []

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"