[project]
name = "dmddl"
version = "0.2.5"
description = "cli tool for creating insert script from ddl script"
authors = [
    {name = "HoJLter",email = "hojlter.work@gmail.com"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic (>=2.11.4,<3.0.0)",
    "pydantic-settings (>=2.9.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
dmddl = "dmddl.cli:main"
