[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lumix"
version = "0.0.6"
readme = "README.md"
description = "A llm Python package."
requires-python = ">=3.10"
authors = [{ name = "chensy cao", email = "chensy.cao@foxmail.com" }]
maintainers = [{ name = "chensy cao", email = "chensy.cao@foxmail.com" }]
keywords = ["LLM", "Agent"]
homepage = "https://caochensy.github.io/lumix/"
repository = "https://github.com/CaoChensy/lumix.git"
license = { text = "MIT" }
classifiers = [
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

packages = [
    { include = "lumix" },
]

dependencies = [
    "pandas>=1.0",
    "requests>=2.32.3",
    "pydantic>=2.8.2",
    "numpy>=1.23.5",
    "tqdm>=4.65.0",
    "colorama>=0.4.6",
    "scikit-image>=0.25.2",
    "PyMuPDF>=1.25.4",
    "openpyxl>=3.1.5",
    "chardet>=5.2.0",
    "bs4>=0.0.2",
    "black>=24.10.0",
    "langchain_text_splitters>=0.3.7",
]


[project.optional-dependencies]
mkdocs = [
    "mkdocs-glightbox>=0.4.0",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-material>=9.5.42",
    "mkdocstrings>=0.26.2",
    "mkdocs-git-revision-date-localized-plugin>=1.3.0",
    "mkdocs-git-committers-plugin-2>=2.4.1",
    "mkdocs-git-authors-plugin>=0.9.0",
    "mkdocs-rss-plugin>=1.15.0",
]

[tool.uv]
dev-dependencies = ["pyright>=1.1.389", "ruff>=0.7.3"]
