[project]
name = "rotate_group_words"
version = "0.3.0"
description = ""
authors = [
    {name = "TSX",email = "miladtsx@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "rotate_group_words", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
main = "rotate_group_words.main:main"