[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "CW-DoublePendulum"
version = "0.3.2"
description = "A Python package that uses NumPy and Matplotlib to simulate an interactive double pendulum."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
  { name = "Chase Worsley", email = "worsleychase@gmail.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "numpy",
  "matplotlib"
]

[project.urls]
Homepage = "https://github.com/Worsleychase/InteractiveDoublePendulum"

[project.scripts]
CWDoublePendulum = "CWDoublePendulum.sim:runSim"

[tool.setuptools]
packages = ["CWDoublePendulum"]

[tool.setuptools.package-data]
CWDoublePendulum = ["testHash.txt"]