[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "async_orch"
version = "0.1.1"
authors = [
  { name="Chakshu", email="chaks.gautam@gmail.com" },
]
description = "async_orch is a Python library designed for building and managing asynchronous task pipelines."
readme = "README.md"
requires-python = ">=3.11"
license = { file="LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Framework :: AsyncIO",
]
dependencies = [
    "aiobreaker>=0.5.0", 
]

[project.urls]
"Homepage" = "https://github.com/ChakshuGautam/async_orch"
"Bug Tracker" = "https://github.com/ChakshuGautam/async_orch/issues"
"Documentation" = "https://github.com/ChakshuGautam/async_orch/blob/main/docs/wiki.md"

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.20.0",
    "backoff>=2.0.0", # Added as it's used in examples and thus tests
    "pytest-cov>=4.0.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
