[project]
name = "assertme"
version = "0.1.0.dev16"
description = "Utilities for asserting without caring (much)"
authors = [
    { name = "Gerard SolÃ©", email = "g.sole.ca@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dateutil (>=2.9.0.post0,<3.0.0)",
    "types-python-dateutil (>=2.9.0.20241206,<3.0.0.0)",
    "pydantic (>=2.5.0,<3.0.0)"
]

[project.urls]
Repository = "https://github.com/GerardSoleCa/assertme.git"
Issues = "https://github.com/GerardSoleCa/assertme/issues"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
ruff = "^0.11.7"
isort = "^6.0.1"
pytest-random-order = "^1.1.1"
pytest-cov = "^6.1.1"
mypy = "^1.15.0"
xenon = "^0.9.3"
pydantic = { extras = ["email"], version = ">=2.5.0,<3.0.0" }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = """
    --random-order
    --color=yes
    --cov --cov-branch --cov-report=xml --cov-report=html
    --junitxml=junit.xml -o junit_family=legacy
"""

[tool.mypy]
python_version = "3.11"
plugins = "pydantic.mypy"
packages = "assertme,tests"
warn_return_any = true
warn_unused_configs = true
warn_unreachable = true
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.isort]
profile = "black"
lines_after_imports = 2
