[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "CW-DoublePendulum"
version = "0.1.0"
description = "A Python package that uses NumPy and Matplotlib to simulate an interactive double pendulum."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
  { name = "Chase Worsley", email = "your_email@example.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "numpy",
  "matplotlib"
]

[project.urls]
Homepage = "https://github.com/Worsleychase/InteractiveDoublePendulum"
