[project]
name = "mcp-paperless-ngx"
version = "0.1.3"
description = "A MCP server for Paperless-ngx"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
 "mcp>=1.7.1",
 "pypaperless>=4.0.0",
]
[[project.authors]]
name = "Simon Erhardt"
email = "simon@erhardt.consulting"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-paperless-ngx = "mcp_paperless_ngx:main"
