[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fileshiftlib"
version = "0.0.1"
requires-python = ">=3.13"
description = "SFTP client!"
readme = "README.md"
authors = [
    { name = "Paulo Portela", email = "portela.paulo@gmail.com" }
]
maintainers = [
    {name = "Paulo Portela", email = "portela.paulo@gmail.com" }
]
license = "BSD-3-Clause"
license-files = ["LICEN[CS]E*"]
keywords = [
    "SFTP", "Python", "FTP", "File Transfer"
]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: MacOS :: MacOS X",
]
dependencies = [
    "paramiko>=3.0"
]

[project.urls]
Homepage = "https://github.com/aghuttun/fileshiftlib"
Documentation = "https://github.com/aghuttun/fileshiftlib/blob/main/README.md"
