[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["yaml", "pytz","requests"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["numpy", "pyreadr", "rpy2", "pandas", "scipy"]
ignore_missing_imports = true

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lightquant"  
version = "0.1.9dev3"  
description = "A lightweight Python library for python utilities for holidays, dates, options and other tools"
readme = "README.md"  # Path to your README file
license = { file = "LICENSE" } 
authors = [
    { name = "Pankaj Sharma", email = "sharma.pankaj.kumar@gmail.com" }
]
dependencies = [
    "numpy==1.21.6",
    "pandas==1.5.3",
    "scikit-learn==1.5.0",
    "scipy==1.11.4",
    "pyyaml==6.0",
    "pyreadr==0.5.0",
    "rpy2==3.5.16",
    "pytz==2024.1",
    "selenium==4.0.0",
    "requests==2.32.3",
    "psutil==7.0.0",
]

[project.urls]
homepage = "https://github.com/yourusername/lightquant"  
repository = "https://github.com/yourusername/lightquant"
