[tool.poetry]
name = "ttk-epay"
version = "0.1.3"
description = ""
authors = ["charen bahaeddine hemmem <charenbahaeddinehemmem@gmail.com>"]
readme = "README.md"

packages = [{ include = "ttk_epay", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
