[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=7,<8",
    "scikit-build-core>=0.7,<0.8",
    "pybind11>=2.12,<2.13",
]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "pyfastlanes"
version = "0.1.0"            # â† hard-coded version
description = "FastLanes File Format"
authors = [{ name = "Azim Afroozeh", email = "azim@cwi.nl" }]
requires-python = ">=3.8"
license = { file = "LICENSE" }

[tool.setuptools-scm]
version_scheme = "release-branch-semver"

[tool.scikit-build.wheel]
license-files = ["LICENSE"]

[tool.cibuildwheel]
test-command = "pytest -q tests"

[tool.scikit-build]
build-dir = "skbuild-editable"
editable.mode = "redirect"
cmake.args = [
    "-DFLS_BUILD_PYTHON=ON",
    "-DFLS_ENABLE_VERBOSE_OUTPUT=ON"
]
