[project]
name = "jasmit_firestarter"
version = "0.2.3"
authors = [
  { name="jasmit", email="jasmit@swbell.net" },
]
description = "Artifacts often useful when starting a new project"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "jasmit-firestarter",
]

[tool.uv.sources]
jasmit-firestarter = { workspace = true }

[project.urls]
#  Homepage = "https://github.com/pypa/sampleproject"
#  Issues = "https://github.com/pypa/sampleproject/issues"


[tool.uv]
package = true

[tool.uv.sources.jasmit_firestarter]
path = "src/jasmit_firestarter"