[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "m4p"
version = "0.3"
authors = [
  { name="Nikolaos Chatzikonstantinou", email="nchatz314@gmail.com" },
]
description = "An implementation of m4 in Python"
readme = "README.txt"
license = "GPL-3.0-or-later"
license-files = ["COPYING"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "attrs >= 24, < 26",
  "lark >= 1.2, < 2",
  "pygnuregex >= 1.1.3, < 2",
]

[project.urls]
Homepage = "https://codeberg.org/annoyingusername/m4p"
Issues = "https://codeberg.org/annoyingusername/m4p/issues"

[project.scripts]
m4p = "m4p.main:main"

[project.optional-dependencies]
tests = [
    "pytest",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
