[tool.poetry]
name = "shellviz"
version = "0.4.2"
description = ""
authors = ["Jean-Marc Skopek <jskopek@gmail.com>"]
readme = "README.md"
include = [
    "shellviz/dist/index.html",
    "shellviz/dist/static/js/main.js",
    "shellviz/dist/static/css/main.css",
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.scripts]
shellviz = "shellviz.cli:cli"  # Command = Module:Function

[tool.poetry.group.dev.dependencies]
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
script = "prepare_dist.py"
