[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opeira"
version = "0.0.7"
description = "OPEIRA - Energy and Process Systems Toolbox"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "opeira" }]
urls = { Homepage = "http://pypi.python.org/pypi/opeira/" }

dependencies = [
    # Add actual dependencies here, e.g. "requests >=2.20.0"
]

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["opeira"]
