[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jc-handy-helpers"
version = "1.1.0"
authors = [
  { name="Jeff Clough", email="jeff@cloughcottage.com" },
]
description = "A collection of useful Python classes and functions."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.11"
dependencies = [
]
keywords = ["utility", "toolkit", "convenience"]
classifiers = [
  "Development Status :: 5 - Production/Stable",  # Adjust as your package matures
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",  # Update if you choose a different license
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jc-handy/handy"
