[project]
name = "lightly-purple"
version = "0.2.23"
description = "Lightly Purple is a lightweight, fast, and easy-to-use data exploration tool for data scientists and engineers."
readme = "USAGE.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]

dependencies = [
    "annotated-types==0.7.0",
    "duckdb-engine>=0.13.5",
    "duckdb>=1.1.3",
    "fastapi>=0.115.5",
    "sqlmodel>=0.0.22",
    "typing-extensions>=4.12.2",
    "uvicorn>=0.32.1",
    "labelformat>=0.1.7",
    "tqdm>=4.65.0",
    "python-dotenv>=1.0.1",
    "eval-type-backport>=0.2.2",
    "xxhash>=3.5.0",
    "scikit-learn==1.3.2",
    "torchmetrics>=1.5.2",
    "faster-coco-eval>=1.6.5",
]

[dependency-groups]
dev = [
    "black>=24.8.0",
    "httpx>=0.27.2",
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
    "ruff>=0.7.4",
    "hatchling>=1.27.0",
    "mypy>=1.14.1",
    "types-tqdm>=4.67.0.20241221",
]
mobileclip = [
    "mobileclip",
]


[tool.mypy]
strict = true
disallow_untyped_defs = true
ignore_missing_imports = false
exclude = [
    "vendor/",
    "src/lightly_purple/server/app.py",
    "src/lightly_purple/server/cache.py",
    "src/lightly_purple/server/db.py",
    "src/lightly_purple/server/models/__init__.py",
    "src/lightly_purple/server/models/tag.py",
    "src/lightly_purple/server/resolvers/annotation.py",
    "src/lightly_purple/server/resolvers/dataset.py",
    "src/lightly_purple/server/resolvers/sample.py",
    "src/lightly_purple/server/resolvers/tag.py",
    "src/lightly_purple/server/routes/api/annotation_label.py",
    "src/lightly_purple/server/routes/api/annotation.py",
    "src/lightly_purple/server/routes/api/dataset_tag.py",
    "src/lightly_purple/server/routes/api/dataset.py",
    "src/lightly_purple/server/routes/api/sample.py",
    "src/lightly_purple/server/routes/healthz.py",
    "src/lightly_purple/server/routes/webapp.py",
    "src/lightly_purple/server/server.py",
    "src/lightly_purple/example_predictions.py",
    "tests/helpers_api.py",
    "tests/server/resolvers/test_annotation.py",
    "tests/server/resolvers/test_dataset.py",
    "tests/server/resolvers/test_sample.py",
    "tests/server/resolvers/test_tag.py",
    "tests/server/routes/api/test_annotation_label.py",
    "tests/server/routes/api/test_annotation.py",
    "tests/server/routes/api/test_dataset_tag.py",
    "tests/server/routes/api/test_dataset.py",
    "tests/server/routes/api/test_sample.py",
    "tests/server/test_server.py",
    "tests/server/resolvers/test_samples_filter.py",
]


[tool.pytest.ini_options]
# Make pytest discover all files in the tests directory. This is useful for showing
# detailed assertion errors outside of the test file, for example when using a helper
# function from `tests/helpers.py`.
python_files = "tests/*.py tests/**/*.py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
only-include = ["src/lightly_purple"]

[tool.hatch.build.targets.wheel]
packages = ["src/lightly_purple"]

[tool.uv.sources]
mobileclip = { path = "vendor/ml-mobileclip" }

[tool.hatch.build]
artifacts = [
    "src/lightly_purple/**/*",
]
