[tool.poetry]
name = "secflash"
version = "0.1.0"
description = "Библиотека для анализа уязвимостей безопасности"
authors = ["saikonohack <saintklovus@gmail.com>"]
readme = "README.md"
packages = [{include = "secflash"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
sqlalchemy = "^2.0.0"
python-dotenv = "^1.0.0"
reportlab = "^4.0.0"
nvdlib = "^0.8.0"
setuptools = "^80.3.1"
babel = "^2.17.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
black = "^23.0.0"
isort = "^5.0.0"
mypy = "^1.0.0"
flake8 = "^6.0.0"
sphinx = "^7.2.0"
sphinx-rtd-theme = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.8"
strict = true
ignore_missing_imports = true 