[tool.poetry]
name = "a-domain-model"
version = "0.1.6"
description = ""
authors = ["AndriiDubonos <andreydubonos1@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "domain_model"}
]

[tool.poetry.dependencies]
python = ">=3.13"
pydantic = "2.11.3"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
