[project]
name = "finance-tools-mcp"
version = "0.0.10"
description = "A Model Context Protocol server for a collection of financial tools, https://github.com/VoxLink-org/finance-tools-mcp, modified from [investor-agent](https://github.com/ferdousbhai/investor-agent)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fredapi>=0.5.2",
    "httpx>=0.28.1",
    "lxml>=5.4.0",
    "mcp[cli]>=1.2.1",
    "pyrate-limiter>=2.10.0",
    "requests-cache>=1.2.1",
    "requests-ratelimiter>=0.7.0",
    "ta-lib-easy>=1.0.3",
    "tabulate>=0.9.0",
    "yfinance[nospam]>=0.2.58",
]
authors = [
    { name = "wanghsinche", email = "wanghsinche@hotmail.com" }
]
keywords = ["investment", "finance", "trading", "agent", "mcp", "model context protocol", "broker", "robinhood", "wallstreetbets"]
classifiers = [
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Office/Business :: Financial",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
]

[project.scripts]
finance-tools-mcp = "src.investor_agent.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
