[project]
name = "ViSound"
version = "0.1.1"
description = "A library to sonify images using Python"
authors = [{ name = "Dheeraj Vittal Shenoy", email = "dheerajshenoy22@email.com" }]
dependencies = [
    "numpy",
    "opencv-python",
]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/dheerajshenoy/ViSound"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
